// Code generated by Modus. DO NOT EDIT.

package main

import (
	"github.com/hypermodeinc/modus/sdk/go/pkg/console"
)

//go:export getSymptomByName
func __modus_GetSymptomByName(name string) Symptom {
	r0, err := GetSymptomByName(name)
	if err != nil {
		console.Error(err.Error())
	}
	return r0
}

